# Generated by Django 5.1.4 on 2026-09-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ref', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('parse', '解析项目源码并产图')], max_length=32)),
                ('state', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败'), ('canceled', '已取消')], default='queued', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('priority', models.SmallIntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.SmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('eta_s', models.IntegerField(blank=True, null=True)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['state', '-priority', 'queued_at'], name='jobs_job_state_c34089_idx'), models.Index(fields=['project_ref', 'state'], name='jobs_job_project_5686d6_idx')],
            },
        ),
    ]
