# Generated by Django 5.1.4 on 2026-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('parse', '解析项目源码并产图'), ('heat_flush', '合并节点热度（Redis → 数据库）')], max_length=32),
        ),
    ]
