# Generated by Django 5.1.4 on 2026-09-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_ref', models.CharField(db_index=True, max_length=64)),
                ('uid', models.CharField(db_index=True, help_text='人类可读标签：<kind>#<相对路径>#<名字>#<重载键>（⚠ 允许重复）', max_length=1024)),
                ('node_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=512)),
                ('qname', models.CharField(blank=True, default='', max_length=512)),
                ('file_path', models.CharField(max_length=1024)),
                ('line', models.IntegerField()),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('lang', models.CharField(max_length=32)),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('doc', models.TextField(blank=True, default='')),
                ('origin', models.CharField(default='parsed', max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['project_ref', 'file_path'], name='graph_node_project_005bca_idx'), models.Index(fields=['project_ref', 'kind'], name='graph_node_project_d07e92_idx'), models.Index(fields=['project_ref', 'lang'], name='graph_node_project_3ab2be_idx')],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_ref', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('origin', models.CharField(default='parsed', max_length=16)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, default='', max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='graph.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='graph.node')),
            ],
            options={
                'indexes': [models.Index(fields=['project_ref', 'from_node', 'type'], name='graph_edge_project_f2c813_idx'), models.Index(fields=['project_ref', 'to_node', 'type'], name='graph_edge_project_115b16_idx')],
            },
        ),
    ]
