# Generated by Django 5.1.4 on 2026-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRevision',
            fields=[
                ('project_ref', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('rev', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '图版本号',
            },
        ),
    ]
