# Generated by Django 5.1.4 on 2026-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_graphrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatFlush',
            fields=[
                ('flush_key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('project_ref', models.CharField(max_length=64)),
                ('metric', models.CharField(max_length=32)),
                ('rows', models.IntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '热度合并批次',
                'indexes': [models.Index(fields=['project_ref', 'metric'], name='graph_heatf_project_54598a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ref', models.CharField(max_length=64)),
                ('metric', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=1024)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '节点热度',
                'indexes': [models.Index(fields=['project_ref', 'metric', '-value'], name='graph_nodeh_project_e5122d_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_ref', 'metric', 'uid'), name='uniq_node_heat')],
            },
        ),
    ]
