# Generated by Django 5.1.4 on 2026-09-19 04:11

import core.refs
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_ref', models.CharField(default=core.refs.new_project_ref, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitee', 'Gitee')], default='', max_length=16)),
                ('repo_url', models.CharField(blank=True, default='', max_length=512)),
                ('commit', models.CharField(blank=True, default='', max_length=64)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'indexes': [models.Index(fields=['is_public', '-created_at'], name='core_projec_is_publ_03b1a1_idx'), models.Index(fields=['owner', '-created_at'], name='core_projec_owner_i_50a4c6_idx')],
            },
        ),
    ]
