# Generated by Django 5.1.4 on 2026-09-19 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appsetting_userprofile_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(db_index=True, max_length=32)),
                ('reason_text', models.CharField(max_length=400)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('suggestion', models.CharField(blank=True, default='', max_length=200)),
                ('decision', models.CharField(choices=[('pending', '待审核'), ('approved', '放行'), ('rejected', '拒绝')], db_index=True, default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '项目审核',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='license_category',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='license_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='license_exception',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='license_spdx',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='price_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='review_state',
            field=models.CharField(choices=[('none', '无需审核'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('active', '正常'), ('hidden', '已隐藏'), ('taken_down', '已下架')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['review_state', '-created_at'], name='core_projec_review__a375e1_idx'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectreview',
            index=models.Index(fields=['decision', '-created_at'], name='core_projec_decisio_58eccc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreview',
            index=models.Index(fields=['project', '-created_at'], name='core_projec_project_90b19a_idx'),
        ),
    ]
