# Generated by Django 5.1.4 on 2026-09-19 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectreview_project_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='auto_decided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='quota_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='repo_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='submitted_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='user_message',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectreview',
            index=models.Index(fields=['submitted_by', '-created_at'], name='core_projec_submitt_39591a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreview',
            index=models.Index(fields=['submitted_by', 'repo_url'], name='core_projec_submitt_b836f0_idx'),
        ),
    ]
