# Generated by Django 5.1.4 on 2026-09-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectreview_auto_decided_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('used_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邀请',
                'indexes': [models.Index(fields=['-created_at'], name='core_invite_created_7c7c28_idx'), models.Index(fields=['created_by', '-created_at'], name='core_invite_created_f6cf14_idx')],
            },
        ),
    ]
