# Generated by Django 5.1.4 on 2026-09-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitee', 'Gitee')], max_length=16)),
                ('action', models.CharField(choices=[('login', '登录 / 注册'), ('publish', '发布项目（需★当场校验归属）')], default='login', max_length=16)),
                ('invite_token', models.CharField(blank=True, default='', max_length=64)),
                ('next_url', models.CharField(blank=True, default='', max_length=512)),
                ('repo', models.CharField(blank=True, default='', max_length=512)),
                ('project_ref', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OAuth 会话',
                'indexes': [models.Index(fields=['expires_at'], name='core_oauths_expires_e5c973_idx'), models.Index(fields=['-created_at'], name='core_oauths_created_13c0d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitee', 'Gitee')], db_index=True, max_length=16)),
                ('provider_user_id', models.CharField(db_index=True, max_length=64)),
                ('login', models.CharField(blank=True, default='', max_length=150)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方身份',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_provider_identity'), models.UniqueConstraint(fields=('user', 'provider'), name='uniq_user_provider')],
            },
        ),
    ]
