# Generated by Django 5.1.4 on 2026-09-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_oauthstate_oauthidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='remember',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=16)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API 令牌',
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_apitok_user_id_9266c3_idx'), models.Index(fields=['expires_at'], name='core_apitok_expires_f4ca50_idx')],
            },
        ),
    ]
