# Generated by Django 5.1.4 on 2026-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_oauthstate_remember_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='intent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
