# Generated by Django 5.1.4 on 2026-09-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_oauthstate_intent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStorage',
            fields=[
                ('project_ref', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('bytes_used', models.BigIntegerField(default=0)),
                ('files_used', models.IntegerField(default=0)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measured_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_storages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目存储占用',
                'indexes': [models.Index(fields=['owner'], name='core_projec_owner_i_a4b520_idx'), models.Index(fields=['-bytes_used'], name='core_projec_bytes_u_5423de_idx')],
            },
        ),
    ]
