# Generated by Django 5.1.4 on 2026-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='graph_built_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='resolved_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
