# Generated by Django 5.1.4 on 2026-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_graph_built_at_project_resolved_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='action',
            field=models.CharField(choices=[('login', '登录 / 注册'), ('publish', '发布项目（需★当场校验归属）'), ('fetch', '拉取代码（需★当场校验归属）')], default='login', max_length=16),
        ),
    ]
